# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: stockbazaar.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11stockbazaar.proto\x12\x0bstockbazaar\"\x1d\n\rLookupRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\",\n\x0blookupReply\x12\r\n\x05price\x18\x01 \x01(\x02\x12\x0e\n\x06volume\x18\x02 \x01(\x05\">\n\x0cTradeRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x12\n\nadd_remove\x18\x02 \x01(\x05\x12\x0c\n\x04type\x18\x03 \x01(\t\"\x1d\n\nTradeReply\x12\x0f\n\x07message\x18\x01 \x01(\x05\",\n\rUpdateRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05price\x18\x02 \x01(\x05\"\x1e\n\x0bUpdateReply\x12\x0f\n\x07message\x18\x01 \x01(\x05\x32\xd0\x01\n\x0bStockHandle\x12@\n\x06Lookup\x12\x1a.stockbazaar.LookupRequest\x1a\x18.stockbazaar.lookupReply\"\x00\x12=\n\x05Trade\x12\x19.stockbazaar.TradeRequest\x1a\x17.stockbazaar.TradeReply\"\x00\x12@\n\x06Update\x12\x1a.stockbazaar.UpdateRequest\x1a\x18.stockbazaar.UpdateReply\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stockbazaar_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _LOOKUPREQUEST._serialized_start=34
  _LOOKUPREQUEST._serialized_end=63
  _LOOKUPREPLY._serialized_start=65
  _LOOKUPREPLY._serialized_end=109
  _TRADEREQUEST._serialized_start=111
  _TRADEREQUEST._serialized_end=173
  _TRADEREPLY._serialized_start=175
  _TRADEREPLY._serialized_end=204
  _UPDATEREQUEST._serialized_start=206
  _UPDATEREQUEST._serialized_end=250
  _UPDATEREPLY._serialized_start=252
  _UPDATEREPLY._serialized_end=282
  _STOCKHANDLE._serialized_start=285
  _STOCKHANDLE._serialized_end=493
# @@protoc_insertion_point(module_scope)
