# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import stockbazaar_pb2 as stockbazaar__pb2


class StockHandleStub(object):
    """The greeting service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Lookup = channel.unary_unary(
                '/stockbazaar.StockHandle/Lookup',
                request_serializer=stockbazaar__pb2.LookupRequest.SerializeToString,
                response_deserializer=stockbazaar__pb2.lookupReply.FromString,
                )
        self.Trade = channel.unary_unary(
                '/stockbazaar.StockHandle/Trade',
                request_serializer=stockbazaar__pb2.TradeRequest.SerializeToString,
                response_deserializer=stockbazaar__pb2.TradeReply.FromString,
                )
        self.Update = channel.unary_unary(
                '/stockbazaar.StockHandle/Update',
                request_serializer=stockbazaar__pb2.UpdateRequest.SerializeToString,
                response_deserializer=stockbazaar__pb2.UpdateReply.FromString,
                )


class StockHandleServicer(object):
    """The greeting service definition.
    """

    def Lookup(self, request, context):
        """Sends a greeting
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Trade(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Update(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StockHandleServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Lookup': grpc.unary_unary_rpc_method_handler(
                    servicer.Lookup,
                    request_deserializer=stockbazaar__pb2.LookupRequest.FromString,
                    response_serializer=stockbazaar__pb2.lookupReply.SerializeToString,
            ),
            'Trade': grpc.unary_unary_rpc_method_handler(
                    servicer.Trade,
                    request_deserializer=stockbazaar__pb2.TradeRequest.FromString,
                    response_serializer=stockbazaar__pb2.TradeReply.SerializeToString,
            ),
            'Update': grpc.unary_unary_rpc_method_handler(
                    servicer.Update,
                    request_deserializer=stockbazaar__pb2.UpdateRequest.FromString,
                    response_serializer=stockbazaar__pb2.UpdateReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'stockbazaar.StockHandle', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class StockHandle(object):
    """The greeting service definition.
    """

    @staticmethod
    def Lookup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/stockbazaar.StockHandle/Lookup',
            stockbazaar__pb2.LookupRequest.SerializeToString,
            stockbazaar__pb2.lookupReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Trade(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/stockbazaar.StockHandle/Trade',
            stockbazaar__pb2.TradeRequest.SerializeToString,
            stockbazaar__pb2.TradeReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Update(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/stockbazaar.StockHandle/Update',
            stockbazaar__pb2.UpdateRequest.SerializeToString,
            stockbazaar__pb2.UpdateReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
